# Assuming ~/.dotfiles
if [ -d "$HOME/.dotfiles" ]; then
  DOTFILES_DIR="$HOME/.dotfiles"
else
  echo "Unable to find dotfiles, exiting."
  return
fi

# Make utilities available
export PATH="$DOTFILES_DIR/bin:$PATH"

# Set environment variables
for DOTFILE in "$DOTFILES_DIR"/profile/env_*; do
  [[ $DOTFILE == *sh ]] && . "$DOTFILE"
  [[ $DOTFILE == *macos ]] && [ is-macos ] && . "$DOTFILE"
done

# Clean up
unset DOTFILE

# Export
export DOTFILES_DIR
