# If not running interactively, don't do anything
[ -z "$PS1" ] && return

# Stub
for DOTFILE in "$DOTFILES_DIR"/profile/app_*; do
  [[ $DOTFILE == *sh ]] && . "$DOTFILE"
  [[ $DOTFILE == *macos ]] && [ is-macos ] && . "$DOTFILE"
done

# Hook for extra/custom stuff
DOTFILES_EXTRA_DIR="$HOME/.extra"
if [ -d "$DOTFILES_EXTRA_DIR" ]; then
  for EXTRAFILE in "$DOTFILES_EXTRA_DIR"/runcom/*.sh; do
    [ -f "$EXTRAFILE" ] && . "$EXTRAFILE"
  done
fi

# Clean up
unset DOTFILE EXTRAFILE

# Export
export DOTFILES_EXTRA_DIR

# Update dotfiles on new shell
(cd ~/.dotfiles && git pull)

test -e "${HOME}/.iterm2_shell_integration.zsh" && source "${HOME}/.iterm2_shell_integration.zsh"
