---
- hosts: localhost
  gather_facts: true

  roles:
    - role: elliotweiser.osx-command-line-tools
    - role: geerlingguy.mac.homebrew
      tags: ['homebrew']
    - role: dotfiles
      tags: ['dotfiles']
    - role: geerlingguy.mac.mas
      when: mas_installed_apps or mas_installed_app_ids
      tags: ['mas']
    - role: geerlingguy.mac.dock
      when: configure_dock
      tags: ['dock']
    - role: ansible-role-iterm2
      tags: ['iterm2']

  tasks:
    - import_tasks: tasks/cameracontroller.yml
      tags: ['cameracontroller']
    - command: "xattr -rd com.apple.quarantine '{{ item }}'"
      become: true
      tags: ['qlFix']
      loop:
        - "{{ ansible_user_dir }}/Library/QuickLook/QLStephen.qlgenerator"
        - "{{ ansible_user_dir }}/Library/QuickLook/QLColorCode.qlgenerator"
        - "/Applications/Cask/QLMarkdown.app"